print ("hello world!")
print ("hello world!")
print ("hello world!")
print('hello everyone!')
print('hello all!')
print(((((("Don't touch this file!" + "!!!")))))) #(and this string!!!)
print("Hello everybody")
